import { describe, expect, it } from 'vitest';
import { allLocalities } from '@/lib/locations';

/**
 * Hand-verified council corrections for suburbs that are NOT indexable.
 *
 * tests/unit/tier1-councils.test.ts pins the councils that render on indexable
 * pages. This pins the ones that do not — yet. The upstream dataset is
 * regenerated by `npm run locations:build`, which re-downloads the source and
 * rebuilds every locality from it, so a correction that lives only in the
 * generated JSON would be silently undone by the next run. Each entry below
 * corresponds to an override in scripts/build-locations.mts and fails here if
 * that override is dropped.
 *
 * These matter because a Tier 3 suburb is one promotion away from rendering
 * its council as a public fact, and the promotion is the moment nobody
 * re-checks the data.
 *
 * Found by scripts/audit-councils.mjs except where noted.
 */
const VERIFIED_TIER_3_COUNCILS: Record<string, string> = {
  // Swapped with each other in the source: Coburg carried Darebin, Northcote
  // carried Moreland. Invisible to the centroid audit — the two councils
  // adjoin, so neither suburb is a distance outlier from the wrong centre.
  // Surfaced by hand when Northcote came up as a promotion candidate.
  'VIC|coburg': 'Moreland',
  'VIC|northcote': 'Darebin',

  // Tagged Casey, which is the same error already corrected for Dandenong
  // South; the parent suburb was missed. It is the seat of the council named
  // after it.
  'VIC|dandenong': 'Greater Dandenong',
};

describe('hand-verified council overrides survive a dataset rebuild', () => {
  it('renders the corrected council for every pinned suburb', () => {
    for (const [key, expected] of Object.entries(VERIFIED_TIER_3_COUNCILS)) {
      const [state, slug] = key.split('|');
      const locality = allLocalities().find((l) => l.state === state && l.slug === slug);
      expect(locality, `${key} is not in the dataset`).toBeDefined();
      expect(locality!.council.name, key).toBe(expected);
    }
  });

  /**
   * Coburg and Northcote were swapped, so asserting each one individually
   * would still pass if a future edit swapped them back in the override map
   * itself. Asserting they differ is the cheap guard against that.
   */
  it('keeps Coburg and Northcote in different councils', () => {
    const all = allLocalities();
    const coburg = all.find((l) => l.state === 'VIC' && l.slug === 'coburg');
    const northcote = all.find((l) => l.state === 'VIC' && l.slug === 'northcote');
    expect(coburg!.council.name).not.toBe(northcote!.council.name);
  });

  /**
   * Tullamarine is deliberately left on Brimbank despite being the strongest
   * Tier 1 outlier the audit reports — see the note in build-locations.mts and
   * the split-suburb rule in tier1-councils.test.ts. Pinned here too so that
   * "fixing" it to Hume fails in the place that explains why it is not a bug.
   */
  it('leaves Tullamarine on Brimbank, the council holding its commercial core', () => {
    const tullamarine = allLocalities().find((l) => l.state === 'VIC' && l.slug === 'tullamarine');
    expect(tullamarine!.council.name).toBe('Brimbank');
  });
});
